import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import { AutumnWrapper } from "@/components/AutumnWrapper";
import { AuthUIWrapper } from "@/components/AuthUIWrapper";
import { Toaster } from "sonner"
import { NavBar } from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ConvexClientProvider>
            <AutumnWrapper>
              <AuthUIWrapper>
                {/* <NavBar /> */}
                {children}
              </AuthUIWrapper>
            </AutumnWrapper>
          </ConvexClientProvider>
        
        <Toaster />
      </body>
    </html>
  );
}
